version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - echo "installing something and updating"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - apt-get update && apt-get install vim
            - echo "we will run some tests"
            - grep -Fq "Nkuli" index.html
    post_build:
        commands:
            - echo "we are in the post build phase"
            
